version: '3.8'

services:
  petcare-auth:
    build: .
    ports:
      - "5042:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_SERVER=db
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Passw0rd
      - DB_NAME=PetCareAuth
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    command: ["./wait-for-db.sh"]

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: YourStrong@Passw0rd
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    ports:
      - "14433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

volumes:
  sql_data: 